apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: fiapmicroservicos-catalog-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: ASPNETCORE_ENVIRONMENT

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: RABBITMQ_HOST

            - name: PAYMENT_PROCESSED_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: PAYMENT_PROCESSED_QUEUE

            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: JWT_ISSUER

            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: JWT_AUDIENCE

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: JWT_SECRET

            - name: ORDER_PLACED_ENTITY_NAME
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: ORDER_PLACED_ENTITY_NAME

            - name: PAYMENT_PROCESSED_ENTITY_NAME
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: PAYMENT_PROCESSED_ENTITY_NAME